version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - npm install -g npm@7
      - npm install

  pre_build:
    commands:
      - echo "Building the Next.js app..."
      - npm run build

  build:
    commands:
      - echo "Exporting the Next.js app for static hosting..."
      - npm run export

  post_build:
    commands:
      - echo "Deployment completed!"

artifacts:
  base-directory: out
  files:
    - '**/*'
